# Generated by Django 3.0.8 on 2020-08-13 10:55

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200813_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A slug to identify posts by this category', populate_from='name'),
        ),
    ]
